version: '3'

services:
  # MariaDB 서비스
  mariadb:
    build:
      context: ./MariaDB
      dockerfile: Dockerfile-mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - docker-network
    restart: on-failure
    env_file:
      - .env  # 환경 변수를 .env 파일에서 읽어옵니다.

  # NGINX 서비스
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    volumes:
      - wordpress_files:/var/www/wordpress
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    env_file:
      - .env  # 환경 변수를 .env 파일에서 읽어옵니다.
    restart: on-failure
  


  # WordPress 서비스
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile-wordpress
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - docker-network
    env_file:
      - .env
    command: ["sh", "-c", "/usr/local/bin/init-wp.sh"]
    restart: on-failure
    depends_on:
      - mariadb

# 볼륨 설정
volumes:
  wordpress_files:
    
  wordpress_db:
    

# 네트워크 설정
networks:
  docker-network:

