# Use Alpine
FROM alpine:3.14

# Install nginx
RUN apk add --no-cache nginx openssl

# Copy configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates (Replace these lines with your actual certificate paths)
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=CA/O=Acme, Inc./CN=example.com" -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt

# Expose ports
EXPOSE 443

# # Start nginx
CMD ["nginx", "-g", "daemon off;"]

# 환경변수를 적용하기 위한 새로운 CMD 명령어
# CMD /bin/sh -c "envsubst '\$DOMAIN_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"


