# Alpine Linux를 기반으로 하는 MariaDB 이미지
FROM alpine:3.17

# 필요한 디렉터리 생성
RUN mkdir -p /run/mysqld

# MariaDB 패키지 설치
RUN apk add --no-cache mariadb mariadb-client

# 이제 mysql 사용자와 그룹이 존재하므로 chown을 실행
RUN chown -R mysql:mysql /run/mysqld

# MariaDB 설정 파일 복사
COPY my.cnf /etc/my.cnf

# 데이터베이스 초기화 스크립트 추가
COPY init-db.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init-db.sh

# MariaDB 실행
CMD ["sh", "/usr/local/bin/init-db.sh"]
